% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Oct-2022 21:47:39
%  MATLAB version: 9.12.0.2039608 (R2022a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('BestChromosome.mat');

bestChromosome = saveVarsMat.bestChromosome; % <1x13484 double> too many elements

clear saveVarsMat;
